name: Node Snyk Workflow

on:
  push:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./frontend   # 👉 adjust to match your project

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk test
        run: snyk test
        working-directory: ./frontend   # 👉 adjust to match your project
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
