name: Node Snyk Workflow

on:
  push:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./mern/frontend

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk test and generate JSON report
        run: snyk test --json > snyk-report.json
        working-directory: ./mern/frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Show summary of vulnerabilities by severity
        run: |
          cd ./mern/frontend
          HIGH=$(jq '[.vulnerabilities[] | select(.severity=="high")] | length' snyk-report.json)
          MEDIUM=$(jq '[.vulnerabilities[] | select(.severity=="medium")] | length' snyk-report.json)
          LOW=$(jq '[.vulnerabilities[] | select(.severity=="low")] | length' snyk-report.json)
          echo "🔒 Snyk Vulnerability Summary:"
          echo "🟥 High: $HIGH"
          echo "🟧 Medium: $MEDIUM"
          echo "🟨 Low: $LOW"
        shell: bash

      - name: Monitor project in Snyk dashboard
        run: snyk monitor
        working-directory: ./mern/frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
